// Auto-generated - edit asset file dtc.csv
const int dtc_index [] PROGMEM = {1000,1001,1100,1101,1102,1103,1110,1112,1113,1114,1116,1117,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1141,1142,1143,1144,1150,1151,1152,1153,1154,1169,1170,1173,1182,1189,1190,1191,1194,1195,1196,1197,1213,1221,1222,1226,1235,1236,1248,1250,1251,1252,1260,1270,1279,1298,1309,1312,1318,1319,1345,1351,1352,1353,1354,1358,1359,1360,1361,1362,1364,1365,1382,1387,1390,1400,1401,1402,1405,1406,1407,1408,1409,1410,1412,1415,1416,1417,1418,1419,1439,1443,1444,1445,1446,1449,1450,1451,1455,1456,1457,1460,1464,1473,1474,1475,1476,1477,1479,1485,1486,1487,1491,1492,1493,1495,1496,1497,1498,1499,1500,1501,1502,1504,1505,1506,1507,1508,1509,1510,1511,1512,1515,1521,1522,1523,1524,1525,1526,1527,1528,1529,1540,1562,1566,1569,1570,1600,1601,1602,1602,1603,1604,1605,1608,1609,1621,1622,1623,1624,1627,1628,1630,1631,1632,1633,1634,1645,1649,1650,1651,1652,1680,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1701,1702,1703,1705,1706,1708,1709,1710,1711,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1729,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1751,1752,1754,1756,1757,1759,1761,1762,1763,1764,1765,1767,1770,1771,1772,1775,1776,1777,1780,1780,1781,1783,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1900,1901};
const char *dtc_data[268] = {
"OBD II Monitor Testing Not Completed",
"Unable to Achieve Self-Test Function Or SCP Error",
"MAF Sensor Circuit Intermittent",
"MAF Sensor Circuit Out Of Self-Test Range",
"MAF Sensor Signal Inconsistent With TPS",
"MAF Sensor Signal Inconsistent With Engine Speed",
"MAF Sensor Signal (Dynamic Chamber) Circuit",
"MAF Sensor Circuit Intermittent",
"MAF Sensor Signal (Dynamic Chamber) Circuit",
"MAF Sensor Circuit Low Input",
"ECT Sensor Circuit Out Of Self Test Range",
"ECT Sensor Signal Intermittent",
"TPS Out Of Range Low",
"TPS Signal Not Consistent With MAF Signal",
"Throttle Position Stuck Closed",
"Throttle Position Stuck Open",
"TPS Signal Out Of Self Test Range",
"TPS Signal Intermittent",
"Throttle Position (Narrow Range) Sensor Circuit",
"HO2S Bank 1 Sensor 2 Heater Not On During Key On Engine Running Self Test",
"HO2S Bank 1 Sensor 1 Signals Swapped In Key On Engine Running Self Test",
"Downstream H02S Sensors Swapped",
"HO2S Bank 1 Sensor 1 Not Switching (Fuel Control Limit Reached)",
"HO2S Bank 1 Sensor 1 Signal Below 0.45v (A/F Ratio Too Lean)",
"HO2S Bank 1 Sensor 1 Signal Above 0.45v (A/F Ratio Too Rich)",
"Bank 1 Fuel Control Shifted Lean",
"Bank 1 Fuel Control Shifted Rich",
"HO2S Bank 1 Sensor 1 Heater Circuit Low Input",
"HO2S Bank 1 Sensor 1 Heater Circuit High Input",
"HO2S Bank 1 Sensor 2 Not Switching (Fuel Control Limit Reached)",
"HO2S Bank 1 Sensor 2 Signal Above 0.45v (A/F Ratio Too Rich)",
"HO2S Bank 1 Sensor 2 Heater Circuit Low Input",
"HO2S Bank 1 Sensor 2 Heater Circuit High Input",
"HO2S Bank 1 Sensor 3 Signal Below 0.45v (A/F Ratio Too Lean)",
"HO2S Bank 1 Sensor 3 Signal Above 0.45v (A/F Ratio Too Rich)",
"HO2S Bank 2 Sensor 1 Not Switching (Fuel Control Limit Reached)",
"HO2S Bank 2 Sensor 1 Signal Below 0.45v (A/F Ratio Too Lean)",
"HO2S Bank 2 Sensor 1 Signal Above 0.45v (A/F Ratio Too Rich)",
"Bank 2 Fuel Control Shifted Lean(FAOSC)",
"Bank 2 Fuel Control Shifted Rich (FAOSC)",
"HO2S Bank 1 Sensor 1 Circuit Fixed (Bank 1 Sensor 1)",
"HO2S Bank 1 Sensor 1 Circuit Fixed (Bank 1 Sensor 1)",
"HO2S Bank 2 Sensor 1 Circuit Fixed (Bank 2 Sensor 1)",
"Fuel Shut Off Solenoid Circuit",
"ump Speed Signal",
"Calibration Resistor Out Of Range",
"TP (Controlled) Circuit",
"ECM, PCM, A/D Converter",
"EGR Boost Sensor Circuit",
"Ignition Switch Start Circuit",
"Mileage Switch Circuit",
"Start Injector Circuit",
"Traction Control System",
"Traction Control Output Circuit",
"Control Sleeve Sensor Cicuit",
"Fuel Pump Control Circuit",
"Fuel Pump Control Out Range",
"Turbo Boost Pressure Not Detected",
"ressure Regulator Control Solenoid Circuit",
"Air Mixture Solenoid Circuit",
"ressure Regulator Control Solenoid '2' Circuit",
"Anti-Theft System Signal Detected - Engine Disabled",
"Engine RPM or Vehicle Speed Limit Reached",
"Control Sleeve Sensor Circuit Range/Performance",
"Injector Driver Module Failure",
"Misfire Detection Monitor",
"Injection Pump Timing Actuator Circuit",
"Injection Timing Piston Position Sensor Circuit",
"Injection Timing Piston Position Sensor Circuit Range/Performance",
"No CMP or SGC Signal",
"Ignition Diagnostic Monitor Signal Lost To PCM Or Out Of Range",
"Ignition Coil 'A' Primary Circuit",
"Ignition Coil 'B' Primary Circuit",
"Ignition Coil 'C' Primary Circuit",
"Ignition Diagnostic Monitor Signal Out Of Self Test Range",
"SPOUT Signal Lost To Powertrain Control Module Or Out Of Range",
"Ignition Coil 'A' Secondary Circuit",
"Ignition Coil 'B' Secondary Circuit",
"Ignition Coil 'C' Secondary Circuit",
"Ignition Coil Primary Circuit",
"Ignition Coil Secondary Circuit",
"Camshaft Position Timing Solenoid #1 Circuit",
"Camshaft Position Timing Solenoid #2 Circuit",
"Octane Adjust Shorting Bar Out or Circuit Open",
"DPFE Sensor Circuit Low Input",
"DPFE Sensor Circuit High Input",
"EGR Valve Position Sensor Circuit",
"DPFE Sensor Upstream Hose Off Or Plugged",
"DPFE Sensor Downstream Hose Off Or Plugged",
"No EGR Flow Detected",
"EGR System Flow Out Of Key On Engine Running Self Test Range",
"EGR Vacuum Regulator Solenoid Circuit",
"EGR Boost Solenoid Valve Stuck",
"Exhaust Gas Recirculation Valve Frozen",
"Air Pump Circuit",
"ort Air Circuit",
"ort Air Relief Circuit",
"Split Air #1 Circuit",
"Split Air #2 Circuit",
"Floor Temp Switch Circuit",
"EVAP System Purge Flow Fault",
"EVAP Purge Flow Sensor Circuit Low Voltage",
"EVAP Purge Flow Sensor Circuit High Voltage",
"Evaporative Vacuum Solenoid Circuit",
"Evaporative Check Solenoid Circuit",
"Unable To Bleed Up Fuel Tank Vacuum",
"Canister Vent Solenoid Circuit",
"Fuel Tank Level Sensor Circuit",
"Fuel Tank Temperature Sensor Circuit",
"urge Solenoid Control System",
"Wide Open Throttle A/C Cut-Off Relay Circuit",
"Air Conditioning Control Signal Circuit",
"Fan Circuit Open (VLCM)",
"Fan Control (Primary Winding) Circuit",
"Fan Relay (Low) Circuit",
"Fan Relay (High) Circuit",
"Additional Fan Relay Circuit",
"Fan Control (Condenser Primary) Circuit",
"EGR Vacuum Solenoid Circuit",
"EGR Vent Solenoid Circuit",
"EGR-CHK (Boost) Solenoid Circuit",
"Secondary Switch Solenoid Circuit",
"APLSOL Solenoid Circuit",
"RCNT Solenoid Circuit",
"TCSPL Solenoid Circuit",
"EGR Valve Motor Coil '1' Open or Shorted",
"EGR Valve Motor Coil '2' Open or Shorted",
"EGR Valve Motor Coil '3' Open or Shorted",
"EGR Valve Motor Coil '4' Open or Shorted",
"Vehicle Speed Sensor Intermittent Signal",
"Vehicle Speed Sensor Out Of Self Test Range",
"Vehicle Speed Sensor Circuit Error",
"Idle Air Control Solenoid Circuit Intermittent",
"Idle Air Control System At Adaptive Clip",
"Idle Air Control System Overspeed Detected",
"Idle Air Control System Underspeed Detected",
"Bypass Air Solenoid '1' Circuit",
"Bypass Air Solenoid '2' Circuit",
"Idle Signal Circuit",
"Idle Switch (Electric Control Throttle) Circuit",
"VTCS Fault",
"Electric Current Circuit",
"VRIS Solenoid '1' Circuit",
"VRIS Solenoid '2 Circuit",
"VICS Solenoid Circuit",
"Charge Air Cooler Bypass Solenoid Circuit",
"ABV Vacuum Solenoid Circuit",
"ABV Vent Solenoid Circuit",
"Bypass Air Solenoid (Accelerate Warmup) Circuit",
"Subsidiary Throttle Valve Solenoid Circuit",
"L/C Atmospheric Balance Air Control Valve Circuit",
"ABV System Fault",
"owertrain Control Module +B Voltage Low",
"TCM B+ Voltage Low",
"IMRC Circuit Low",
"IMRC Circuit High",
"Loss Of KAM Power, Circuit Open",
"owertrain Control Module Communication Line To TCM Error",
"owertrain Control Module Communication Line To TCM Error",
"Immobilizer System Communication Error With Powertrain Control Module",
"Immobilizer System Fault",
"Immobilizer System Fault",
"owertrain Control Module Keep Alive Memory Test Error",
"owertrain Control Module (ECM CPU) DTC Test Fault",
"owertrain Control Module (ECM CPU) Knock Sensor Circuit",
"Immobilizer System Fault",
"Immobilizer System Fault",
"Immobilizer System Fault",
"Immobilizer System Fault",
"owertrain Control Module (ECM/TCS) Line Communication Error",
"owertrain Control Module (ECM/TCS) Any Line Communication Error",
"Alternator Regulator #1 Control Circuit",
"Generator Output Voltage Signal (No Output)",
"Battery Voltage Monitor Circuit",
"Battery Overcharge Fault",
"Generator Terminal 'B' Circuit Open",
"Fuel Pump Resistor Switch Circuit",
"Fuel Injection Pump Module",
"ower Steering Pressure Switch Out Of Range Fault",
"ower Steering Pressure Switch Circuit",
"ower Steering Pressure Switch Circuit",
"Metering Oil Pump Failure",
"Metering Oil Pump Failure",
"Metering Oil Pump Temperature Sensor Circuit",
"Metering Oil Pump Position Sensor Circuit",
"Metering Oil Pump Stepping Motor Cont. Circuit",
"Metering Oil Pump Stepping Motor Cont. Circuit",
"Metering Oil Pump Stepping Motor Cont. Circuit",
"Metering Oil Pump Stepping Motor Cont. Circuit",
"Oil Pressure Control Solenoid Circuit",
"Wastegate Solenoid Circuit",
"Turbo Pressure Control Solenoid Circuit",
"Turbo Control Solenoid Circuit",
"Turbo Charge Control Circuit",
"Turbo Charge Relief Circuit",
"Transmission Range Sensor Reverse Engagement Error",
"Transmission Range Sensor Circuit Intermittent",
"Brake On/Off Switch Out Of Self Test Range",
"Transmission Range Sensor Out Of Self Test Range",
"High Vehicle Speed Observed In Park",
"Clutch Switch Circuit",
"Clutch Pedal Position Switch Circuit",
"Transmission Control Module Solenoid/Internal Ground Circuit",
"Transmission Fluid Temperature Sensor Circuit Out Of Self Test Range",
"Transmission Fluid Temperature Sensor Circuit",
"Shift Solenoid '1' Mechanical Fault",
"Shift Solenoid '2' Mechanical Fault",
"Shift Solenoid '3' Mechanical Fault",
"Shift Solenoid '4' Mechanical Fault",
"Transmission Fluid Temperature Sensor Circuit",
"Engine Torque Signal",
"Vehicle Speed Sensor '2' Signal Error",
"Gear 1 Incorrect Ratio",
"Gear 2 Incorrect Ratio",
"Gear 3 Incorrect Ratio",
"Gear 4 Incorrect Ratio",
"Transmission 4x4 Low Switch Error",
"First Gear Switch Circuit Failure",
"Second Gear Switch Circuit Failure",
"Lockup Solenoid",
"Shift Time Error",
"Slip Solenoid",
"Torque Converter Clutch Solenoid Mechanical Fault",
"Torque Converter Clutch Control Electrical Fault",
"Torque Converter Clutch Solenoid Shorted",
"Torque Converter Clutch Failed On - TCIL Is On",
"Torque Converter Clutch Solenoid Mechanical Fault",
"Line Pressure Solenoid",
"Electronic Pressure Control Solenoid Circuit Open",
"Electronic Pressure Control Solenoid Circuit",
"ressure Control Solenoid 'A'",
"Electronic Pressure Control Solenoid Circuit Low",
"Transmission Shift Solenoid 'A' Mechanical Fault",
"Transmission Shift Solenoid 'A' Circuit Shorted",
"Transmission Coast Clutch Solenoid Electrical Fault",
"Transmission Shift Solenoid 'B' Mechanical Fault",
"Transmission Shift Solenoid 'B' Circuit Shorted",
"2-4 Brake Failsafe Valve Malfunction",
"Transmission Shift Solenoid '3' Mechanical Fault",
"Transmission SS3/SS4/OD Band Fault",
"Low And Reverse Brake Pressure Switch Circuit",
"Low And Reverse Brake Failsafe Valve Malfunction",
"Transmission 3-2 Timing Solenoid Valve",
"Torque Converter Clutch Solenoid Circuit",
"Clutch Solenoid Circuit",
"TPS Circuit Open To Transmission Control Module",
"TPS Circuit Shorted To Transmission Control Module",
"Torque Down Signal #1 Circuit",
"Toqure Down Signal #2 Circuit",
"Torque Down Response Signal Circuit",
"Transmission Control Switch Circuit",
"Overdrive Off Switch Not Cycled During The Self Test",
"Transmission 4x4 Low Switch Out Of Range Fault",
"Transmission Fluid Temperature High Input",
"ressure Control Solenoid 'B' Circuit Open",
"ressure Control Solenoid 'B' Circuit Shorted",
"TP (Mechanical) Circuit",
"TP (Electric) Circuit",
"Barometer Pressure Circuit",
"Intake Air Volume Circuit",
"owertrain Control Module Battery Direct Power Circuit",
"Idle Switch Circuit",
"Kick Down Switch Circuit",
"/N Switch Open Or Short Circuit",
"Coolant Temperature Circuit",
"Hold Switch Circuit",
"Turbine Speed Sensor Circuit Intermittent",
"Torque Converter Clutch Circuit Intermittent",
};
